osx_image: xcode7.3
language: objective-c
before_install: cd SwiftExample && bundle exec pod install
script: xcodebuild clean test -workspace SwiftExample.xcworkspace -scheme SwiftExample -destination platform='iOS Simulator',name='iPhone 5s' -sdk iphonesimulator | xcpretty -t -c
